<?php

/**
 * @file 
 * Drupal module part of reset_node_counter.
 */

include_once(module_load_include('inc', 'reset_node_counter'));

/**
 * Implements hook_help().
 */
function reset_node_counter_help($path, $arg) {
  $output = '';  
  switch ($path) {
    case "admin/help#reset_node_counter":
      $filepath = dirname(__FILE__) . '/README.md';
      if (file_exists($filepath)) {
        $readme = file_get_contents($filepath);
      }
      if (module_exists('markdown')) {
        $filters = module_invoke('markdown', 'filter_info');
        $info = $filters['filter_markdown'];
    
        if (function_exists($info['process callback'])) {
          $output = $info['process callback']($readme, NULL);
        }
      }
      else {
        $output = '<pre>' . $readme . '</pre>';
      }
  }
  return $output;
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function reset_node_counter_form_node_form_alter(&$form, &$form_state, $form_id) {
  $form['options']['reset_node_counter'] = array(
    '#type' => 'checkbox',
    '#title' => t('Reset node counter'),
    '#default_value' => 0,
  );
  $form['actions']['submit']['#submit'][] = 'reset_node_counter_submit';
}

/**
 * Additional form submit function.
 */
function reset_node_counter_submit($form) {
  if ($form['options']['reset_node_counter']['#value']) {
    reset_node_counter_reset($form['nid']['#value']);   
  }
}
