<?php

/**
 * @file reset_node_counter module
 */

/**
 * Implements hook_help().
 */
function reset_node_counter_help($path, $arg) {
  $output = '';  
  switch ($path) {
    case "admin/help#reset_node_counter_":
      $output = '<p>'.  t("Reset node counter") .'</p>';
      break;
  }
  return $output;
}
/**
 * Implements hook_form_alter().
 */
function reset_node_counter_form_alter(&$form, &$form_state, $form_id) {
  if ($form['#id'] == 'node-form') { 
    $form['options']['reset_node_counter'] = array(
      '#type' => 'checkbox',
      '#title' => t('Reset node counter'),
      '#default_value' => 0,
    );
    $form['#submit'][] = 'reset_node_counter_submit';
  }
}

/**
 * Additional form submit function.
 */
function reset_node_counter_submit($node) {
  if ($node['#post']['reset_node_counter']) {
    reset_node_counter_reset($node['nid']['#value']);   
  }
}

/**
 * Callback for resetting a counter for a node.
 *
 * @param int $nid 
 *   Node id of correspoding node.
 */
function reset_node_counter_reset($nid) {
   db_query('DELETE FROM {node_counter} WHERE nid = %d', $nid);
} 
